### ISSUE TITLE
Google drive imported file have .bin extension 

### ISSUE THREAD

**Issue by amgschnappi** [nextcloud/integration_google#176] opened 2024-08-10 14:59 UTC
### Which version of integration_google are you using?

Latest

### Which version of Nextcloud are you using?

Latest

### Describe the Bug

Files which where downloaded from google drive via integration app have .bin as extension 

### Expected Behavior

Extension should be correct. Not additional.bin

### To Reproduce

Import google drive files and check the extension. 
![Screenshot_20240810_164210_Firefox_Original](https://github.com/user-attachments/assets/c18fbc62-d348-456d-a388-1809b309ff93)

**Comment by marcelklehr** [comment] 2024-08-12 06:32
Aaah, damn. Confirmed. Thank you for the feedback.

**Comment by marcelklehr** [comment] 2024-08-12 06:45
Can you try again with v3.0.2? I'm really sorry about the trouble

**Comment by amgschnappi** [comment] 2024-08-12 17:27
Still reproducible..

**Comment by marcelklehr** [comment] 2024-08-13 07:15
Have you started from scratch? Existing file won't be fixed by v3.0.2

**Comment by amgschnappi** [comment] 2024-08-14 06:31
I see that docx have correct extension. But all the pdfs are messed up.

**Comment by marcelklehr** [comment] 2024-09-19 12:22
I cannot reproduce this, anymore.

**Closed** 2024-09-20 08:04 UTC
Labels: bug, high priority
