### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by QazCetelic** [nextcloud/integration_google#137] opened 2023-04-19 15:00 UTC
First I get an message saying the app isn't verified
![image](https://user-images.githubusercontent.com/51381523/233116073-a4a4f663-6bab-4f5b-baf7-83f69c70080f.png)
After pressing continue I get the following error
![image](https://user-images.githubusercontent.com/51381523/233116767-79b71457-e679-421f-a052-354e806e3c1a.png)

I'm using version 1.0.9

**Comment by toonvank** [comment] 2023-05-07 19:33
Same issue here

**Comment by bardo** [comment] 2023-05-18 16:51
Are you using Firefox? If so, this might be a duplicate of #110, and using Chrome/Chromium should work around the issue.

**Comment by QazCetelic** [comment] 2023-05-21 10:42
> Are you using Firefox? If so, this might be a duplicate of #110, and using Chrome/Chromium should work around the issue.

I was, thanks for the workaround.

![image](https://github.com/nextcloud/integration_google/assets/51381523/1603a66e-b84f-4cc7-8b33-c56fa7213a83)

**Closed** 2023-06-01 09:35 UTC
