### ISSUE TITLE
Operation timed out after 30001 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by thom4parisot** [nextcloud/integration_google#24] opened 2020-11-02 15:10 UTC
For some reasons, timeouts happen:

```
[core] Error: GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at <<closure>>

 0. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 155
    GuzzleHttp\Handler\CurlFactory::createRejection(GuzzleHttp\Handl ... l}, {errno: 28,error ... "})
 1. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 105
    GuzzleHttp\Handler\CurlFactory::finishError(GuzzleHttp\Handler\CurlHandler {}, GuzzleHttp\Handl ... l}, GuzzleHttp\Handler\CurlFactory {})
 2. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php line 43
    GuzzleHttp\Handler\CurlFactory::finish(GuzzleHttp\Handler\CurlHandler {}, GuzzleHttp\Handl ... l}, GuzzleHttp\Handler\CurlFactory {})
 3. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php line 28
    GuzzleHttp\Handler\CurlHandler->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 4. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php line 51
    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensitive parameters replaced ***")
 5. /var/www/html/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php line 37
    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensitive parameters replaced ***")
 6. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 29
    GuzzleHttp\PrepareBodyMiddleware->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 7. /var/www/html/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 70
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 8. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 59
    GuzzleHttp\RedirectMiddleware->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 9. /var/www/html/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php line 71
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
10. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 361
    GuzzleHttp\HandlerStack->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
11. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 163
    GuzzleHttp\Client->transfer("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
12. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 183
    GuzzleHttp\Client->requestAsync("get", GuzzleHttp\Psr7\Uri {}, {verify: "/var/w ... }})
13. /var/www/html/lib/private/Http/Client/Client.php line 233
    GuzzleHttp\Client->request("get", "https://www.goo ... n", {verify: "/var/w ... e})
14. /var/www/html/custom_apps/integration_google/lib/Service/GoogleAPIService.php line 290
    OC\Http\Client\Client->get("https://www.goo ... n", {save_to: "/tmp/ ... }})
15. /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php line 330
    OCA\Google\Service\GoogleAPIService->simpleDownload("ya29.a0AfH6SMBu ... V", "admin", "https://www.goo ... n", "/tmp/oc_tmp_ny8ir5", {mimeType: "appl ... "})
16. /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php line 215
    OCA\Google\Service\GoogleDriveAPIService->getFile("ya29.a0AfH6SMBu ... V", "admin", {kind: "drive#fi ... }}, {1d0KsPmWYAZlMym ... }}, OC\Files\Node\Folder {})
17. /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php line 129
    OCA\Google\Service\GoogleDriveAPIService->importFiles("ya29.a0AfH6SMBu ... V", "admin", "Importation de Google Drive", 500000000, 108)
18. /var/www/html/custom_apps/integration_google/lib/BackgroundJob/ImportDriveJob.php line 36
    OCA\Google\Service\GoogleDriveAPIService->importDriveJob("admin")
19. /var/www/html/lib/public/BackgroundJob/Job.php line 80
    OCA\Google\BackgroundJob\ImportDriveJob->run({user_id: "admin"})
20. /var/www/html/lib/public/BackgroundJob/QueuedJob.php line 48
    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
21. /var/www/html/cron.php line 127
    OCP\BackgroundJob\QueuedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-11-02T13:56:41+00:00
```

Sounds like there is a [backoff plugin](https://guzzle3.readthedocs.io/plugins/backoff-plugin.html) to deal with this with very little pain.

What do you think?

**Comment by eneiluj** [comment] 2020-11-03 15:45
I think the problem here is that we reach the client timeout. A backoff plugin won't solve that.

I tried to remove the timeout in the app. Let's see if it is still set to an external value. Could you try v0.0.13 which I just released?

Thanks a lot for the bug reports.

**Comment by oncletom** [comment] 2020-11-03 19:49
OK, I'm confused with the "client" notion (and which part of the software is responsible for it), but it's not important.

I updated and restarted the import. So far it's progressing beyond the previous times (154 files so far; until now the best was 110 files).

**Comment by eneiluj** [comment] 2020-11-03 23:16
The "entity" which downloads the files is your Nextcloud server. To do so, it uses an HTTP client (GuzzleHttp). When this client makes requests (ask things to the API, download files...), there is a timeout. This is what caused the exception you pasted.

If it went further than before, I have good hopes it will succeed now. At least, removing the timeout had an actual effect. Yay!

**Comment by oncletom** [comment] 2020-11-04 10:32
1800 files (23%) have been imported but it stopped because of another error yesterday evening:

```
[PHP] Error: Error: fwrite(): write of 4096 bytes failed with errno=28 No space left on device at /var/www/html/3rdparty/guzzlehttp/psr7/src/Stream.php#244 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(8, "fwrite(): write ... e", "/var/www/html/3 ... p", 244, {string: "*** se ... "})
 1. /var/www/html/3rdparty/guzzlehttp/psr7/src/Stream.php line 244
    fwrite(null, "*** sensitive parameter replaced ***")
 2. /var/www/html/3rdparty/guzzlehttp/psr7/src/StreamDecoratorTrait.php line 136
    GuzzleHttp\Psr7\Stream->write("*** sensitive parameter replaced ***")
 3. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 395
    GuzzleHttp\Psr7\LazyOpenStream->write("*** sensitive parameter replaced ***")
 4. <<closure>>
    GuzzleHttp\Handler\CurlFactory->GuzzleHttp\Handler\{closure}("*** sensitive parameters replaced ***")
 5. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php line 40
    curl_exec("*** sensitive parameter replaced ***")
 6. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php line 28
    GuzzleHttp\Handler\CurlHandler->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 7. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php line 51
    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensitive parameters replaced ***")
 8. /var/www/html/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php line 37
    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensitive parameters replaced ***")
 9. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 29
    GuzzleHttp\PrepareBodyMiddleware->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
10. /var/www/html/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 70
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
11. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 59
    GuzzleHttp\RedirectMiddleware->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
12. /var/www/html/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php line 71
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
13. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 361
    GuzzleHttp\HandlerStack->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
14. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 163
    GuzzleHttp\Client->transfer("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
15. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 183
    GuzzleHttp\Client->requestAsync("get", GuzzleHttp\Psr7\Uri {}, {verify: "/var/w ... }})
16. /var/www/html/lib/private/Http/Client/Client.php line 233
    GuzzleHttp\Client->request("get", "https://www.goo ... a", {verify: "/var/w ... e})
17. /var/www/html/custom_apps/integration_google/lib/Service/GoogleAPIService.php line 299
    OC\Http\Client\Client->get("https://www.goo ... a", {save_to: "/tmp/ ... }})
18. /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php line 295
    OCA\Google\Service\GoogleAPIService->simpleDownload("ya29.A0AfH6SMDo ... x", "admin", "https://www.goo ... a", "/tmp/oc_tmp_LVtMAu")
19. /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php line 215
    OCA\Google\Service\GoogleDriveAPIService->getFile("ya29.A0AfH6SMDo ... x", "admin", {kind: "drive#fi ... e}, {1d0KsPmWYAZlMym ... }}, OC\Files\Node\Folder {})
20. /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php line 129
    OCA\Google\Service\GoogleDriveAPIService->importFiles("ya29.A0AfH6SMDo ... x", "admin", "Importation de Google Drive", 500000000, 1802)
21. /var/www/html/custom_apps/integration_google/lib/BackgroundJob/ImportDriveJob.php line 36
    OCA\Google\Service\GoogleDriveAPIService->importDriveJob("admin")
22. /var/www/html/lib/public/BackgroundJob/Job.php line 80
    OCA\Google\BackgroundJob\ImportDriveJob->run({user_id: "admin"})
23. /var/www/html/lib/public/BackgroundJob/QueuedJob.php line 48
    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
24. /var/www/html/cron.php line 127
    OCP\BackgroundJob\QueuedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-11-03T21:26:36+00:00
```

I run Nextcloud in a Docker container, with `/var/www/html` being a mapped folder.
So it sounds like temporary files fill the container internal volume over the time.

It sounds the drive autocleaned itself by 3GB in the meantime — but it does not prevent the import to fail:

```
# docker exec nextcloud df -H
Filesystem      Size  Used Avail Use% Mounted on
overlay          21G   17G  3.0G  85% /
tmpfs            68M     0   68M   0% /dev
tmpfs            17G     0   17G   0% /sys/fs/cgroup
shm              68M     0   68M   0% /dev/shm
/dev/md3         21G   17G  3.0G  85% /etc/hosts
/dev/md4        4.0T   20G  3.7T   1% /var/www/html
tmpfs            17G     0   17G   0% /proc/acpi
tmpfs            17G     0   17G   0% /proc/scsi
tmpfs            17G     0   17G   0% /sys/firmware
```

**Comment by eneiluj** [comment] 2020-11-05 00:43
Ok we're almost there. Silly mistake. The tmp files were left there so they were only deleted when the background job had finished. They are now deleted directly after having been copied. Import will still fail for you if at least one of your drive files is bigger than 3 GB. If not, should be fine now.

Could you get v0.0.14, delete the "Importation de google drive" directory and try to import again (to make sure the "no space left" bug is gone)?

Thanks a looot for your patience and your help there.

**Comment by eneiluj** [comment] 2020-11-05 00:54
Btw, it would be much better to avoid storing tmp files. It turn out Guzzle is able to download in a stream (so the file could directly be written in Nextcloud storage) but there is a bug in their option validation which prevents to do that... Too bad. For the moment, tmp files are good enough though.

**Comment by oncletom** [comment] 2020-11-05 11:53
Hm, I still face the issue. I will clear some space and start with a fresh container, just in case.

**Comment by eneiluj** [comment] 2020-11-05 11:57
Do you know if one of your drive files is bigger than 3 GB?

**Comment by oncletom** [comment] 2020-11-05 12:07
The largest file on my drive is 622MB 😞

**Comment by eneiluj** [comment] 2020-11-05 13:22
Wow this is strange then. I don't know what is taking so much space. What the app does is pretty straightforward:

For each drive file:
* download it in a temp location
* then copy it (in small chunks to avoid the memory issue :grin:) in NC storage
* then delete the temp file

The only reason I can think of is that you have less than 600 MB space left in the partition where the docker container has its /. So the information the container displays is not what's actually available outside. Only a supposition...

v0.0.15 is out. In this one I tried to avoid the crash and put the file name for which there was a problem in the logs.
It will let you know which file triggered the problem.

**Comment by oncletom** [comment] 2020-11-05 22:11
Aaaaand it went well after I mapped `/tmp` to my large external storage.
Import succeeded successfully.

I realised a 12GB file has been shared with me… but was not "added to my drive". It was still imported.
I wonder though if it should have been the case—I somewhat expected to import the 4GB scanned by the plugin, and the entirety of all the files shared with me—unadded to my Drive.

**Comment by eneiluj** [comment] 2020-11-06 18:42
> it went well after I mapped /tmp to my large external storage

Great! We did it! It would still be better to avoid this full storage issue by solving the Guzzle bug. I keep that in my todo list.

> I somewhat expected to import the 4GB scanned by the plugin, and the entirety of all the files shared with me—unadded to my Drive.

You're right. This is now an option. Size display has also been improved, it now makes the difference between your own storage and the shared content. It will be included in next release which is coming soon.

Let's close this one :tada:

**Comment by eneiluj** [comment] 2020-11-07 02:55
I finally found the problem and managed to directly download to the target file instead of using a temp file.

If one day you find time and you feel like it, I'm very interested in a real life test with the kind of context you had in the beginning: small / (small /tmp in fact) and big files to import. It would be good to confirm the 2 issues are really gone:
* memory (let's make sure guzzle uses a low amount of it when downloading to a stream)
* space (let's make sure guzzle really directly writes in the stream and does not use too much space)

Cheers

**Comment by oncletom** [comment] 2020-11-08 09:10
This update broke the import (it does not go beyond a certain amount of files, and the importer screen does not state anything regarding the progress):

```
[PHP] Error: Error: fclose(): supplied resource is not a valid stream resource at /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php#335 at <<closure>>

0. <<closure>>
   OC\Log\ErrorHandler::onError(2, "fclose(): suppl ... e", "/var/www/html/c ... p", 335, {accessToken: "y ... }})
1. /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php line 335
   fclose(null)
2. /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php line 252
   OCA\Google\Service\GoogleDriveAPIService->getFile("ya29.A0AfH6SMCA ... A", "admin", {id: "1YAg9V6eO5 ... e}, {1BjHoal12rHZl3h ... }}, OC\Files\Node\Folder {})
3. /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php line 150
   OCA\Google\Service\GoogleDriveAPIService->importFiles("ya29.A0AfH6SMCA ... A", "admin", "Importation de Google Drive", 500000000, 0)
4. /var/www/html/custom_apps/integration_google/lib/BackgroundJob/ImportDriveJob.php line 36
   OCA\Google\Service\GoogleDriveAPIService->importDriveJob("admin")
5. /var/www/html/lib/public/BackgroundJob/Job.php line 80
   OCA\Google\BackgroundJob\ImportDriveJob->run({user_id: "admin"})
6. /var/www/html/lib/public/BackgroundJob/QueuedJob.php line 48
   OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
7. /var/www/html/cron.php line 127
   OCP\BackgroundJob\QueuedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-11-07T07:26:30+00:00
```

It happens many times.

---

Another pair of errors/warnings happen too:

```
[PHP] Error: Error: fread(): read of 8192 bytes failed with errno=9 Bad file descriptor at /var/www/html/3rdparty/icewind/streams/src/Wrapper.php#91 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(8, "fread(): read o ... r", "/var/www/html/3 ... p", 91, {count: 8192})
 1. /var/www/html/3rdparty/icewind/streams/src/Wrapper.php line 91
    fread(null, 8192)
 2. /var/www/html/3rdparty/icewind/streams/src/CallbackWrapper.php line 98
    Icewind\Streams\Wrapper->stream_read(8192)
 3. <<closure>>
    Icewind\Streams\CallbackWrapper->stream_read(8192)
 4. /var/www/html/3rdparty/guzzlehttp/psr7/src/Stream.php line 225
    fread(null, 120)
 5. /var/www/html/3rdparty/guzzlehttp/psr7/src/functions.php line 867
    GuzzleHttp\Psr7\Stream->read(120)
 6. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php line 127
    GuzzleHttp\Psr7\get_message_body_summary("*** sensitive parameter replaced ***")
 7. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php line 107
    GuzzleHttp\Exception\RequestException::getResponseBodySummary("*** sensitive parameter replaced ***")
 8. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 65
    GuzzleHttp\Exception\RequestException::create(GuzzleHttp\Psr7\Request {}, "*** sensitive parameter replaced ***")
 9. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 203
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
10. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 156
    GuzzleHttp\Promise\Promise::callHandler(1, "*** sensitive parameter replaced ***", [GuzzleHttp\Prom ... l])
11. /var/www/html/3rdparty/guzzlehttp/promises/src/TaskQueue.php line 47
    GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}("*** sensitive parameters replaced ***")
12. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 246
    GuzzleHttp\Promise\TaskQueue->run(true)
13. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 223
    GuzzleHttp\Promise\Promise->invokeWaitFn()
14. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 267
    GuzzleHttp\Promise\Promise->waitIfPending()
15. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 225
    GuzzleHttp\Promise\Promise->invokeWaitList()
16. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 62
    GuzzleHttp\Promise\Promise->waitIfPending()
17. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 183
    GuzzleHttp\Promise\Promise->wait()
18. /var/www/html/lib/private/Http/Client/Client.php line 233
    GuzzleHttp\Client->request("get", "https://www.goo ... a", {verify: "/var/w ... e})
19. /var/www/html/custom_apps/integration_google/lib/Service/GoogleAPIService.php line 300
    OC\Http\Client\Client->get("https://www.goo ... a", {sink: null,time ... }})
20. /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php line 333
    OCA\Google\Service\GoogleAPIService->simpleDownload("ya29.A0AfH6SMCA ... A", "admin", "https://www.goo ... a", null)
21. /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php line 252
    OCA\Google\Service\GoogleDriveAPIService->getFile("ya29.A0AfH6SMCA ... A", "admin", {id: "1cV2oIlhaT ... e}, {1BjHoal12rHZl3h ... }}, OC\Files\Node\Folder {})
22. /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php line 150
    OCA\Google\Service\GoogleDriveAPIService->importFiles("ya29.A0AfH6SMCA ... A", "admin", "Importation de Google Drive", 500000000, 0)
23. /var/www/html/custom_apps/integration_google/lib/BackgroundJob/ImportDriveJob.php line 36
    OCA\Google\Service\GoogleDriveAPIService->importDriveJob("admin")
24. /var/www/html/lib/public/BackgroundJob/Job.php line 80
    OCA\Google\BackgroundJob\ImportDriveJob->run({user_id: "admin"})
25. /var/www/html/lib/public/BackgroundJob/QueuedJob.php line 48
    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
26. /var/www/html/cron.php line 127
    OCP\BackgroundJob\QueuedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-11-07T07:26:25+00:00
```

With this following warning:

```
[integration_google] Warning: Google Drive error downloading file Annexe technique (projets en Ã©mergence) (2018) : Unable to read from stream

at 2020-11-07T07:26:25+00:00
```

**Comment by eneiluj** [comment] 2020-11-08 14:55
Neverending story... After a deep search in Nextcloud File/Node implementation, the only reason that could cause `fopen` to return `null` (that what we see in your logs) would be that the file name is invalid. It looks like there is a wrongly interpreted character in `Annexe technique (projets en Ã©mergence) (2018)`. Could you give me this file name as it appear in drive? I tried to reproduce the bug with files named `Annexe technique (projets en émergence) (2018)` and `Annexe technique (projets en Émergence) (2018)` but it works fine. If it's ok with you, it would be nice to have the full file path so I can try to reproduce the bug.

If this file is not too personal, you could also share it with my test google account: `nyugglee@gmail.com`.

Thanks a lot for your patience.

**Comment by oncletom** [comment] 2020-11-08 16:02
Well, the name is `Annexe technique (projets en Ã©mergence) (2018)` 😅

Here are similar warnings:

```
[integration_google] Warning: Google Drive error downloading file Diagramme de Gantt (2018) : Unable to read from stream

at 2020-11-07T07:26:26+00:00
```

```
[integration_google] Warning: Google Drive error downloading file Modèle Engagement de confidentialité - CartoBio : Unable to read from stream

at 2020-11-07T07:24:47+00:00
```

I realise only 3 of them appear in the logs.

---

Also to give you an idea, the logs mostly look like this:

![image](https://user-images.githubusercontent.com/138627/98470107-e6e51e00-21e3-11eb-978f-5a996dfa963f.png)

**Comment by eneiluj** [comment] 2020-11-08 16:18
Thanks for the feedback.

The `fclose()` problem is just a consequence of the real problem which is that `fopen` refuses to open some created files and I suspect it's about the names...

Is this happening only with files which names contain parenthesis?

A potential solution here would be to fallback to temp file download if the output stream has not been sucessfully created...but it's not very satisfying. I would like to make it work properly :grin:.

Could you remove the parenthesis in those file names and retry to import? We're going to make it :smile:.

**Comment by oncletom** [comment] 2020-11-08 21:15
I shall mention I have plenty of `fileNotDownloadable` warnings like the following:

```
[integration_google] Warning: Google Drive error downloading file Freebird Technical Architecture v1.0 : Client error: `GET https://www.googleapis.com/drive/v3/files/1KH0r7capG-u5r3xW8XehFym3pRTaOo-9D3N6pXd5Btc?alt=media` resulted in a `403 Forbidden` response:
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "fileNotDownloadable",
    "message": "Only files (truncated...)


at 2020-11-05T19:10:53+00:00
```

I'm trying with `v0.0.18`.

**Comment by marcelklehr** [comment] 2023-06-02 09:46
Closing due to lack of activity.

**Closed by marcelklehr** 2023-06-02 09:46 UTC
