### ISSUE TITLE
Not importing "Website" and "Notes" fields for Contacts

### ISSUE THREAD

**Issue by cairobraga** [nextcloud/integration_google#96] opened 2022-01-04 02:57 UTC
Hello!

I'm using Nextcloud 22.2.3 on a YUNOHOST environment. The Contacts app is version 4.0.7 and Google Integration 1.0.6.

When I import my contacts list from my Google Account, it fails to parse the "Website" and "Notes" fields from Google. They have direct equivalents on the fields available both under the Contacts app and the CardDAV specs. So this is basically a request for the dev team to consider looking into it, I guess.

Thanks in advance, happy new year!

**Comment by zgypa** [comment] 2022-12-22 13:58
Yeah, this is a deal breaker for me. I have so much info in the Notes field, i cannot give it up. I'm currently trying alternate ways, but i still have to find a way which imports 100%. Mind you, i have 6.5k entries.

**Comment by zgypa** [comment] 2022-12-22 14:32
I took a look at the code, this fix looks pretty trivial. If i remember correctly, there simply is no reference to Notes and Website, and one needs only to add those fields. I can tackle this in 2023-W01, if you like, you can assign this to me.

**Comment by julien-nc** [comment] 2022-12-22 14:50
Thanks @zgypa. It was actually so quick to do I just did it. Notes and websites are now imported. Any other missing field?

**Closed** 2022-12-23 09:40 UTC

**Comment by zgypa** [comment] 2022-12-29 15:03
@julien-nc : i am noticing the website URLs show up as "https\\://..." instead of "https://..."

**Comment by julien-nc** [comment] 2022-12-30 11:00
This does not happen to me. Website values appear correctly
* in the Contacts app
* if I export an imported contact to vcf: `URL;TYPE=Blog;VALUE=URI:https://plop.org`
* in the json payload received from google:
```
"urls": [
    {
      "metadata": {
        "primary": true,
        "source": {
          "type": "CONTACT",
          "id": "680024520d35c0bd"
        }
      },
      "value": "https://free.fr",
      "type": "work",
      "formattedType": "Work"
    },
    {
      "metadata": {
        "source": {
          "type": "CONTACT",
          "id": "680024520d35c0bd"
        }
      },
      "value": "https://plop.org",
      "type": "blog",
      "formattedType": "Blog"
    }
  ],
```

But in a vcf generated by google, the colon is escaped because colon is used as separator between properties and values: `URL;TYPE=WORK:https\://free.fr`

@zgypa Which version of Nextcloud are you using? I'll try to reproduce this issue.
